import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "@/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading, isError, error } = api.posts.getAll.useQuery();

  if (isLoading) {
    return <p>Loading...</p>;
  }

  if (isError) {
    return <p>{error.message}</p>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {user.isSignedIn ? (
            <SignOutButton />
          ) : (
            <SignInButton>Login</SignInButton>
          )}
        </div>
        {data.length > 0 ? (
          <ul>
            {data.map((post) => (
              <li key={post.id}>{post.content}</li>
            ))}
          </ul>
        ) : (
          <p>No posts yet</p>
        )}
      </main>
    </>
  );
};

export default Home;
